import 'package:flutter/material.dart';

class GourdData {
  static const Map<String, String> descriptions = {
    'Acorn Squash':
        'This variety is identified by its prominent ridges and characteristic acorn shape, typically featuring hard, dark-green skin. Due to its shape, the Acorn Squash is a perfect vessel for stuffing; it is often halved, roasted, and filled with savory ingredients like sausage, rice, or grains. It is also popularly baked simply with brown sugar, maple syrup, or honey for a sweet side dish, or pureed into a smooth soup.',
    'Bottle Gourd':
        'This gourd can be long and cylindrical or club-shaped, with smooth, pale-to-bright green skin and soft, white flesh. In Filipino and South Asian cuisine, the Bottle Gourd (Upo) is used like a summer squash. It is commonly prepared in savory stir-fries, such as Ginisang Upo (Sautéed Bottle Gourd with ground pork and tomatoes), or added to curries and stews.',
    'Butternut Squash':
        'Defined by its classic bell or pear shape with a smooth, tough, tan-yellow rind, the Butternut Squash yields sweet, dense, deep-orange flesh. It is one of the most versatile winter squashes: it is ideal for making creamy soups (often with sage or apple), roasted simply with maple syrup, cubed for use in risotto, pasta dishes, or stews, or baked into sweet goods like pies and muffins.',
    'Cantaloupe Melon':
        'A round melon identified by its web-like netted rind and deep orange, juicy, sweet flesh. Cantaloupe is primarily used in fresh, uncooked applications. It is often served sliced or cubed for breakfast, in fruit salads, paired famously with salty cured meats like prosciutto, blended into smoothies, or used to make chilled dishes like gazpacho and granita.',
    'Cucamelon':
        'This tiny fruit looks exactly like a miniature, striped watermelon, but is the size of a grape. Given its unique look and cucumber-lime flavor, the Cucamelon is often used raw: tossed whole into salads, added to veggie platters, or used as a unique garnish for cocktails. It is also excellent for pickling, creating a flavorful and crunchy miniature pickle.',
    'Delicata Squash':
        'This squash is elongated and cylindrical, featuring thin, edible, cream-colored skin with dark-green stripes. Because the skin is edible, Delicata Squash is almost always simply sliced into half-moons and roasted until tender. This method makes it a popular addition to salads, bowls, pasta dishes, or a great component for vegetarian tacos and savory galettes.',
    'Hubbard Squash':
        'Known for its massive size and very hard, thick rind that is often bumpy and can be blue, green, or orange. Its golden-orange flesh is dry and starchy, making it an excellent all-purpose cooking squash. Hubbard Squash is traditionally used in recipes where the squash is mashed, such as sweet fillings for pies and custards, or pureed into creamy, hearty soups. It can also be baked whole and stuffed with cornbread or other savory fillings.',
    'Spaghetti Squash':
        'This oval-shaped squash has a hard, smooth, creamy-yellow rind. Its unique feature is that the pale yellow flesh separates into translucent, pasta-like strands when cooked. This makes it a popular low-carb or gluten-free substitute for pasta in many dishes, such as casseroles, baked "spaghetti" with marinara or Alfredo sauces, and as a base for chicken or vegetable bakes.',
    'Turban Gourd':
        'This ornamental gourd is easily recognized by the small, "turban" shape at its top and its brightly mottled, hard shell. While primarily decorative, the flesh of the Turban Gourd is sweet and nutty. It is most frequently baked and pureed, making it suitable for sweet applications like pies and breads, or used in savory recipes such as pureed creamy curried soups.',
    'White Pattypan Squash':
        'This small, round summer squash features scalloped edges and creamy-white skin, yielding tender, mild flesh with a slightly sweet flavor. It is highly versatile: it can be sautéed, grilled, roasted, or eaten raw in salads. Its compact size and shape also make it ideal for stuffing with savory fillings.',
  };

  static const Map<String, Color> labelColors = {
    'Acorn Squash': Color(0xFF7DAA1B),
    'Bottle Gourd': Color(0xFF028944),
    'Butternut Squash': Color(0xFFFCDB6D),
    'Cantaloupe Melon': Color(0xFFFDEB9E),
    'Cucamelon': Color(0xFFb6ff3d),
    'Delicata Squash': Color(0xFFEAB749),
    'Hubbard Squash': Color(0xFF779eb2),
    'Spaghetti Squash': Color(0xFFF2E58F),
    'Turban Gourd': Color(0xFFFF7043),
    'White Pattypan Squash': Color(0xFFAED1BD),
  };

  static const Map<String, List<String>> relatedImages = {
    'Acorn Squash': [
      'assets/images/Acorn_Squash/as_1.jpg',
      'assets/images/Acorn_Squash/as_2.jpg',
      'assets/images/Acorn_Squash/as_3.jpg',
      'assets/images/Acorn_Squash/as_4.jpg',
      'assets/images/Acorn_Squash/as_5.jpg',
      'assets/images/Acorn_Squash/as_6.jpg',
      'assets/images/Acorn_Squash/as_7.jpg',
      'assets/images/Acorn_Squash/as_8.jpg',
      'assets/images/Acorn_Squash/as_9.jpg',
      'assets/images/Acorn_Squash/as_10.jpg',
      'assets/images/Acorn_Squash/as_11.jpg',
      'assets/images/Acorn_Squash/as_12.jpg',
      'assets/images/Acorn_Squash/as_13.jpg',
      'assets/images/Acorn_Squash/as_14.jpg',
      'assets/images/Acorn_Squash/as_15.jpg',
      'assets/images/Acorn_Squash/as_16.jpg',
      'assets/images/Acorn_Squash/as_17.jpg',
      'assets/images/Acorn_Squash/as_18.jpg',
    ],
    'Bottle Gourd': [
      'assets/images/Bottle_Gourd/bg_1.jpg',
      'assets/images/Bottle_Gourd/bg_2.jpg',
      'assets/images/Bottle_Gourd/bg_3.jpg',
      'assets/images/Bottle_Gourd/bg_4.jpg',
      'assets/images/Bottle_Gourd/bg_5.jpg',
      'assets/images/Bottle_Gourd/bg_6.jpg',
      'assets/images/Bottle_Gourd/bg_7.jpg',
      'assets/images/Bottle_Gourd/bg_8.jpg',
      'assets/images/Bottle_Gourd/bg_9.jpg',
      'assets/images/Bottle_Gourd/bg_10.jpg',
      'assets/images/Bottle_Gourd/bg_11.jpg',
      'assets/images/Bottle_Gourd/bg_12.jpg',
      'assets/images/Bottle_Gourd/bg_13.jpg',
      'assets/images/Bottle_Gourd/bg_14.jpg',
      'assets/images/Bottle_Gourd/bg_15.jpg',
      'assets/images/Bottle_Gourd/bg_16.jpg',
      'assets/images/Bottle_Gourd/bg_17.jpg',
      'assets/images/Bottle_Gourd/bg_18.jpg',
    ],
    'Butternut Squash': [
      'assets/images/Butternut_Squash/bs_1.jpg',
      'assets/images/Butternut_Squash/bs_2.jpg',
      'assets/images/Butternut_Squash/bs_3.jpg',
      'assets/images/Butternut_Squash/bs_4.jpg',
      'assets/images/Butternut_Squash/bs_5.jpg',
      'assets/images/Butternut_Squash/bs_6.jpg',
      'assets/images/Butternut_Squash/bs_7.jpg',
      'assets/images/Butternut_Squash/bs_8.jpg',
      'assets/images/Butternut_Squash/bs_9.jpg',
      'assets/images/Butternut_Squash/bs_10.jpg',
      'assets/images/Butternut_Squash/bs_11.jpg',
      'assets/images/Butternut_Squash/bs_12.jpg',
      'assets/images/Butternut_Squash/bs_13.jpg',
      'assets/images/Butternut_Squash/bs_14.jpg',
      'assets/images/Butternut_Squash/bs_15.jpg',
      'assets/images/Butternut_Squash/bs_16.jpg',
      'assets/images/Butternut_Squash/bs_17.jpg',
      'assets/images/Butternut_Squash/bs_18.jpg',
    ],
    'Cantaloupe Melon': [
      'assets/images/Cantaloupe_Melon/cm_1.jpg',
      'assets/images/Cantaloupe_Melon/cm_2.jpg',
      'assets/images/Cantaloupe_Melon/cm_3.jpg',
      'assets/images/Cantaloupe_Melon/cm_4.jpg',
      'assets/images/Cantaloupe_Melon/cm_5.jpg',
      'assets/images/Cantaloupe_Melon/cm_6.jpg',
      'assets/images/Cantaloupe_Melon/cm_7.jpg',
      'assets/images/Cantaloupe_Melon/cm_8.jpg',
      'assets/images/Cantaloupe_Melon/cm_9.jpg',
      'assets/images/Cantaloupe_Melon/cm_10.jpg',
      'assets/images/Cantaloupe_Melon/cm_11.jpg',
      'assets/images/Cantaloupe_Melon/cm_12.jpg',
      'assets/images/Cantaloupe_Melon/cm_13.jpg',
      'assets/images/Cantaloupe_Melon/cm_14.jpg',
      'assets/images/Cantaloupe_Melon/cm_15.jpg',
      'assets/images/Cantaloupe_Melon/cm_16.jpg',
      'assets/images/Cantaloupe_Melon/cm_17.jpg',
      'assets/images/Cantaloupe_Melon/cm_18.jpg',
    ],
    'Cucamelon': [
      'assets/images/Cucamelon/cucamelon_1.jpg',
      'assets/images/Cucamelon/cucamelon_2.jpg',
      'assets/images/Cucamelon/cucamelon_3.jpg',
      'assets/images/Cucamelon/cucamelon_4.jpg',
      'assets/images/Cucamelon/cucamelon_5.jpg',
      'assets/images/Cucamelon/cucamelon_6.jpg',
      'assets/images/Cucamelon/cucamelon_7.jpg',
      'assets/images/Cucamelon/cucamelon_8.jpg',
      'assets/images/Cucamelon/cucamelon_9.jpg',
      'assets/images/Cucamelon/cucamelon_10.jpg',
      'assets/images/Cucamelon/cucamelon_11.jpg',
      'assets/images/Cucamelon/cucamelon_12.jpg',
      'assets/images/Cucamelon/cucamelon_13.jpg',
      'assets/images/Cucamelon/cucamelon_14.jpg',
      'assets/images/Cucamelon/cucamelon_15.jpg',
      'assets/images/Cucamelon/cucamelon_16.jpg',
      'assets/images/Cucamelon/cucamelon_17.jpg',
      'assets/images/Cucamelon/cucamelon_18.jpg',
    ],
    'Delicata Squash': [
      'assets/images/Delicata_Squash/ds_1.jpg',
      'assets/images/Delicata_Squash/ds_2.jpg',
      'assets/images/Delicata_Squash/ds_3.jpg',
      'assets/images/Delicata_Squash/ds_4.jpg',
      'assets/images/Delicata_Squash/ds_5.jpg',
      'assets/images/Delicata_Squash/ds_6.jpg',
      'assets/images/Delicata_Squash/ds_7.jpg',
      'assets/images/Delicata_Squash/ds_8.jpg',
      'assets/images/Delicata_Squash/ds_9.jpg',
      'assets/images/Delicata_Squash/ds_10.jpg',
      'assets/images/Delicata_Squash/ds_11.jpg',
      'assets/images/Delicata_Squash/ds_12.jpg',
      'assets/images/Delicata_Squash/ds_13.jpg',
      'assets/images/Delicata_Squash/ds_14.jpg',
      'assets/images/Delicata_Squash/ds_15.jpg',
      'assets/images/Delicata_Squash/ds_16.jpg',
      'assets/images/Delicata_Squash/ds_17.jpg',
      'assets/images/Delicata_Squash/ds_18.jpg',
    ],
    'Hubbard Squash': [
      'assets/images/Hubbard_Squash/hs_1.jpg',
      'assets/images/Hubbard_Squash/hs_2.jpg',
      'assets/images/Hubbard_Squash/hs_3.jpg',
      'assets/images/Hubbard_Squash/hs_4.jpg',
      'assets/images/Hubbard_Squash/hs_5.jpg',
      'assets/images/Hubbard_Squash/hs_6.jpg',
      'assets/images/Hubbard_Squash/hs_7.jpg',
      'assets/images/Hubbard_Squash/hs_8.jpg',
      'assets/images/Hubbard_Squash/hs_9.jpg',
      'assets/images/Hubbard_Squash/hs_10.jpg',
      'assets/images/Hubbard_Squash/hs_11.jpg',
      'assets/images/Hubbard_Squash/hs_12.jpg',
      'assets/images/Hubbard_Squash/hs_13.jpg',
      'assets/images/Hubbard_Squash/hs_14.jpg',
      'assets/images/Hubbard_Squash/hs_15.jpg',
      'assets/images/Hubbard_Squash/hs_16.jpg',
      'assets/images/Hubbard_Squash/hs_17.jpg',
      'assets/images/Hubbard_Squash/hs_18.jpg',
    ],
    'Spaghetti Squash': [
      'assets/images/Spaghetti_Squash/ss_1.jpg',
      'assets/images/Spaghetti_Squash/ss_2.jpg',
      'assets/images/Spaghetti_Squash/ss_3.jpg',
      'assets/images/Spaghetti_Squash/ss_4.jpg',
      'assets/images/Spaghetti_Squash/ss_5.jpg',
      'assets/images/Spaghetti_Squash/ss_6.jpg',
      'assets/images/Spaghetti_Squash/ss_7.jpg',
      'assets/images/Spaghetti_Squash/ss_8.jpg',
      'assets/images/Spaghetti_Squash/ss_9.jpg',
      'assets/images/Spaghetti_Squash/ss_10.jpg',
      'assets/images/Spaghetti_Squash/ss_11.jpg',
      'assets/images/Spaghetti_Squash/ss_12.jpg',
      'assets/images/Spaghetti_Squash/ss_13.jpg',
      'assets/images/Spaghetti_Squash/ss_14.jpg',
      'assets/images/Spaghetti_Squash/ss_15.jpg',
      'assets/images/Spaghetti_Squash/ss_16.jpg',
      'assets/images/Spaghetti_Squash/ss_17.jpg',
      'assets/images/Spaghetti_Squash/ss_18.jpg',
    ],
    'Turban Gourd': [
      'assets/images/Turban_Gourd/tg_1.jpg',
      'assets/images/Turban_Gourd/tg_2.jpg',
      'assets/images/Turban_Gourd/tg_3.jpg',
      'assets/images/Turban_Gourd/tg_4.jpg',
      'assets/images/Turban_Gourd/tg_5.jpg',
      'assets/images/Turban_Gourd/tg_6.jpg',
      'assets/images/Turban_Gourd/tg_7.jpg',
      'assets/images/Turban_Gourd/tg_8.jpg',
      'assets/images/Turban_Gourd/tg_9.jpg',
      'assets/images/Turban_Gourd/tg_10.jpg',
      'assets/images/Turban_Gourd/tg_11.jpg',
      'assets/images/Turban_Gourd/tg_12.jpg',
      'assets/images/Turban_Gourd/tg_13.jpg',
      'assets/images/Turban_Gourd/tg_14.jpg',
      'assets/images/Turban_Gourd/tg_15.jpg',
      'assets/images/Turban_Gourd/tg_16.jpg',
      'assets/images/Turban_Gourd/tg_17.jpg',
      'assets/images/Turban_Gourd/tg_18.jpg',
    ],
    'White Pattypan Squash': [
      'assets/images/White_Pattypan_Squash/wpp_1.jpg',
      'assets/images/White_Pattypan_Squash/wpp_2.jpg',
      'assets/images/White_Pattypan_Squash/wpp_3.jpg',
      'assets/images/White_Pattypan_Squash/wpp_4.jpg',
      'assets/images/White_Pattypan_Squash/wpp_5.jpg',
      'assets/images/White_Pattypan_Squash/wpp_6.jpg',
      'assets/images/White_Pattypan_Squash/wpp_7.jpg',
      'assets/images/White_Pattypan_Squash/wpp_8.jpg',
      'assets/images/White_Pattypan_Squash/wpp_9.jpg',
      'assets/images/White_Pattypan_Squash/wpp_10.jpg',
      'assets/images/White_Pattypan_Squash/wpp_11.jpg',
      'assets/images/White_Pattypan_Squash/wpp_12.jpg',
      'assets/images/White_Pattypan_Squash/wpp_13.jpg',
      'assets/images/White_Pattypan_Squash/wpp_14.jpg',
      'assets/images/White_Pattypan_Squash/wpp_15.jpg',
      'assets/images/White_Pattypan_Squash/wpp_16.jpg',
      'assets/images/White_Pattypan_Squash/wpp_17.jpg',
      'assets/images/White_Pattypan_Squash/wpp_18.jpg',
    ],
  };
}
